### ISSUE TITLE
getting `ModuleNotFoundError: No module named 'django_cleanup.apps.CleanupConfig'; 'django_cleanup.apps' is not a package`

### ISSUE THREAD

**Issue by singhravi1** [un1t/django-cleanup#48]
I'm getting this issue when using [django cassandra engine](https://github.com/r4fek/django-cassandra-engine/) and run sync_cassandra command.

It traces back to this line, https://github.com/r4fek/django-cassandra-engine/blob/b43f8fddd4bba143f03f73f8bbfc09e6b32c699b/django_cassandra_engine/management/commands/sync_cassandra.py#L33

**Comment by vinnyrose** [comment]
Hi @singhravi1, this is an exception in django-cassandra that points to a bug in the sync_cassandra command which is not considering the new AppConfig formats. As django recommends here: https://docs.djangoproject.com/en/2.2/ref/applications/#for-application-authors 

> New applications should avoid default_app_config. Instead they should require the dotted path to the appropriate AppConfig subclass to be configured explicitly in INSTALLED_APPS.

Ideally they should just be using the App registry api to get a list of apps instead of using `settings.INSTALLED_APPS:`: https://docs.djangoproject.com/en/2.2/ref/applications/#application-registry

As a workaround I believe you can configure INSTALLED_APPS like so:

    INSTALLED_APPS = (
        ...
        'django_cleanup',
    )

However this is not an issue with django_cleanup, and as such I will be closing this issue. If this continues to be an issue for you I would recommend you open an issue with django-cassandra.
