### ISSUE TITLE
Make a Django 3.0 release

### ISSUE THREAD

**Issue by squio** [un1t/django-cleanup#70]
Hello,

It seems the most recent release (4.0.0) is not yet compatible with Django 3.0 while Master is.

Would it be possible to create a stable release which can be installed from Pypi?

**Comment by vinnyrose** [comment]
4.0.0 is compatible with Django 3.0, there are no functional changes on master branch since 4.0.0 was released.

I am working on a major release (5.x) for dropping python 2.6 and the no longer support Django versions. At that time I plan on cherry-picking all the current commits on master to the release/4.0 branch to make a 4.0.1, but there are no further functional changes planned for 4.x.

**Comment by vinnyrose** [comment]
https://pypi.org/project/django-cleanup/4.0.1/
https://pypi.org/project/django-cleanup/5.0.0/
